name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:
    types: [checks_requested]
  workflow_call:
    outputs:
      unsigned-artifact-id:
        description: "Unsigned Installer"
        value: ${{ jobs.build.outputs.unsigned-artifact-id }}

jobs:
  build:
    runs-on: windows-latest
    name: Build
    outputs:
      unsigned-artifact-id: ${{ steps.upload-unsigned.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup rustup
        run: rustup target add i686-pc-windows-msvc

      - name: Build
        run: scripts/build_installer.bat

      - id: upload-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned Installer
          path: dist\windows-chewing-tsf-unsigned.exe
  test-signing:
    needs: [build]
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/code-signing.yml
    with:
      signing-policy-slug: test-signing
      github-artifact-id: ${{ needs.build.outputs.unsigned-artifact-id }}
    secrets:
      api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
